package com.example.designPrinciplesAndAlgo.smartherd

/*
BACKING field is represented by 'field keyword. It just stores the value of its own property.

It is used because usage of property name within its getter or setter throws StackOverflow exception

The backing field is generated by kotlin internally only when it is used in code.

Backing field can never be used in any other methods apart from getter and setter.

*/

fun main(){
val human = Human()
    human.age = 54
    human.age
}

class Human{
    var age = 20
    get() {
       // println("Age is: $age") //throws StackOverflow exception
        println("Age is: $field") // 'field' keyword stores the value of 'age' property
        return field // returns the value of age property
    }
    set(value) {
        if (value>0){
            field = value // assigns the value to age property
            //age = value //Error:StackOverflow exception
        }
    }
    var name:String = "" //No backing field generated, because we are not try to access the same property (name)
    val isOld:Boolean // here also no backing field will be generated as we are not trying to access the same property which is isOld, we are trying to access age
    get() = age>50
}

/*
* Backing field is only generated for those getter or setter
* where the usage of 'field' keyword is required.*/
